# Generated by Django 5.1.3 on 2024-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('bom', 'Bom'), ('ruim', 'Ruim'), ('regular', 'Regular')], max_length=7)),
            ],
        ),
    ]
