# Generated by Django 5.1.3 on 2024-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='Nome da Pessoa')),
                ('car_plate', models.CharField(max_length=10, verbose_name='Placa do Carro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
