# Generated by Django 5.1.3 on 2024-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_populate_checklist_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='Nome da Pessoa')),
                ('car_plate', models.CharField(max_length=10, verbose_name='Placa do Carro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(blank=True, choices=[('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=7, null=True),
        ),
    ]
