# Generated by Django 5.1.3 on 2024-12-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20241212_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistdetail',
            old_name='group_list',
            new_name='group',
        ),
    ]
